# Generated by Django 4.2.16 on 2025-01-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developertechnology',
            old_name='developer_id',
            new_name='developer',
        ),
        migrations.RenameField(
            model_name='developertechnology',
            old_name='technology_id',
            new_name='technology',
        ),
        migrations.RenameField(
            model_name='projecttechnology',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projecttechnology',
            old_name='technology_id',
            new_name='technology',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='developer_id',
            new_name='developer',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
    ]
