# Generated by Django 4.2.16 on 2025-01-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manager', '0002_rename_developer_id_developertechnology_developer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='update_at',
        ),
    ]
