# Generated by Django 4.2.16 on 2025-01-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manager', '0004_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects_manager.developer'),
        ),
    ]
